services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: portfolio-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

    volumes:
      - kafka_data:/tmp/kraft-combined-logs

  kafka-init:
    image: apache/kafka:4.1.1
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: [ "/bin/bash" ]
    command:
      - -c
      - |
        echo "Waiting for Kafka..."

        sleep 30

        echo "Creating topics..."

        /opt/kafka/bin/kafka-topics.sh --bootstrap-server portfolio-kafka:9092 --create --if-not-exists --topic trade-requests --partitions 3 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server portfolio-kafka:9092 --create --if-not-exists --topic trade-executed --partitions 3 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server portfolio-kafka:9092 --create --if-not-exists --topic trade-failed --partitions 3 --replication-factor 1

        echo "Topics created:"
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server portfolio-kafka:9092 --list

volumes:
  kafka_data: